### ISSUE TITLE
Some GP practices in the 2022 data have null or 0 weighted population

### ISSUE THREAD

**Issue by craig-shenton** [nhsx/AIF_Allocation_Tool#14]
suggestion, replace both with a value of 1

**Comment by mattia-ficarelli** [comment]
Fixed with the following approach:
added following line to get_data function 
df = df.fillna(1).replace(0, 1) 

@JRPearson500, do you agree with this approach?

**Comment by JRPearson500** [comment]
Yes, agree.   We discussed this with the team and they saw the benefit without significant impact on the ratios.
