### ISSUE TITLE
Preview to show indexes before weighted figures

### ISSUE THREAD

**Issue by JRPearson500** [nhsx/AIF_Allocation_Tool#18]

**Comment by mattia-ficarelli** [comment]
fixed

**Comment by mattia-ficarelli** [comment]
@JRPearson500 and @craig-shenton this is the order I've placed the columns in: 

I thought that the overall index should come first - followed by the remaining indicies what do you think?

Group / ICB | Overall Index | Health Inequalities Index | Avoidable Mortality Index | Prescribing Index | HCHS Index | Maternity Index | Mental Health Index | Community Index | G&A Index | GP pop | Weighted G&A pop | Weighted Community pop | Weighted Mental Health pop | Weighted Maternity pop | Weighted HCHS pop | Weighted Prescribing pop | Weighted Avoidable Mortality pop | Weighted Health Inequalities pop | Overall Weighted pop |

**Comment by craig-shenton** [comment]
yep there is some logic as to the way the need indices add up to the overall index in the order they are presented on the dashboard, so might go with that.

**Comment by mattia-ficarelli** [comment]
okay will fix

**Comment by mattia-ficarelli** [comment]
Okay fixed to this:

Group / ICB | G&A Index | Community Index | Mental Health Index | Maternity Index | HCHS Index | Prescribing Index | Health Inequalities Index | Avoidable Mortality Index | Overall Index | GP pop | Weighted G&A pop | Weighted Community pop | Weighted Mental Health pop | Weighted Maternity pop | Weighted HCHS pop | Weighted Prescribing pop | Weighted Avoidable Mortality pop | Weighted Health Inequalities pop | Overall Weighted pop|
