### ISSUE TITLE
Need a way to clear the multi-select box on 'save group' press

### ISSUE THREAD

**Issue by craig-shenton** [nhsx/AIF_Allocation_Tool#2]
[https://docs.streamlit.io/library/api-reference/widgets/st.multiselect](https://docs.streamlit.io/library/api-reference/widgets/st.multiselect)

How does `key`, `on_change` work? Can't find any better docs.

**Comment by mattia-ficarelli** [comment]
decided that this feature is not necessary, as a user may not want to clear the multi-select box upon saving a group
