### ISSUE TITLE
Choose map icon for UK GP practice

### ISSUE THREAD

**Issue by craig-shenton** [nhsx/AIF_Allocation_Tool#26]
[https://fontawesome.com/v4.7/icons/](https://fontawesome.com/v4.7/icons/)

**Comment by mattia-ficarelli** [comment]
https://fontawesome.com/v4.7/icon/user-md  or https://fontawesome.com/v4.7/icon/stethoscope ?

**Comment by mattia-ficarelli** [comment]
<img width="713" alt="Screenshot 2021-12-19 at 21 41 30" src="https://user-images.githubusercontent.com/79908979/146690174-b5dcafef-c03d-4673-96fa-91776d5e0ac7.png">

I quite like this? but i also like the medical square

**Comment by mattia-ficarelli** [comment]
fixed
